### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar película por id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Recuperar películas por género
GET http://localhost:1234/movies?genre=action

### Crear una pelicola con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://diariodeunacinefila.wordpress.com/wp-content/uploads/2011/09/poster-de-el-padrino.jpg",
    "genre": ["Drama", "Crime"]
  }